server:
  port: 8023
spring:
  application:
    name: graduation
  kafka:
    bootstrap-servers: hadoop:9092
    producer:
      retries: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      username: yuwen
      password: lyp82nlf
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://hadoop:3306/grad?characterEncoding=UTF-8&serverTimezone=UTC
      url: jdbc:mysql://127.0.0.1:3306/grad?characterEncoding=UTF-8&serverTimezone=UTC
  data:
    hbase:
      quorum: hadoop:2181
      rootDir: hdfs://hadoop:8020/hbase
      nodeParent: /hbase

logging:
  config: classpath:logback-spring.xml


project:
  kafka:
    flume-topic: flume-topic
#    warn-topic: warn-topic
#  hbase:
#    zookeeper:
#      quorum: hadoop
#      property:
#        port: 2181
#  zookeeper:
#    znode:
#      parent: /hbase
#  mysql:
#    host: 127.0.0.1
#    port: 3306
#    username: yuwen
#    password: lyp82nlf
#    binlogName:
#    position: -1
