server:
  port: 8023
spring:
  messages:
    encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: graduation
  kafka:
    bootstrap-servers: hadoop:9092
#    consumer:
#      group-id: flume-kafka-group
#      client-id: flume-kafka-consumer
#      auto-offset-reset: latest
#      enable-auto-commit: false
    producer:
      retries: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      username: yuwen
      password: lyp82nlf
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///grad?autoReconnect=true&characterEncoding=UTF-8&useSSL=false
  data:
    hbase:
      quorum: hadoop:2181
      rootDir: hdfs://hadoop:8020/hbase
      nodeParent: /hbase

logging:
  config: classpath:logback-spring.xml


project:
  kafka:
    flume-topic: flume-topic
    warn-topic: warn-topic
  hbase:
    zookeeper:
      quorum: hadoop
      property:
        port: 2181
  zookeeper:
    znode:
      parent: /hbase

