server:
  port: 8023
  tomcat:
    uri-encoding: UTF-8

spring:
  messages:
    encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: graduation
  kafka:
    bootstrap-servers: hadoop:9092
    consumer:
      group-id: flume-kafka-group
      client-id: flume-kafka-consumer
      auto-offset-reset: latest
      enable-auto-commit: false
    producer:
      retries: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      username: yuwen
      password: lyp82nlf
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///grad?autoReconnect=true&characterEncoding=utf-8&useSSL=false



logging:
  config: classpath:logback-spring.xml

debug: true

project:
  kafka:
    topic: flume-topic
  hbase:
    zookeeper:
      quorum: hadoop
      property:
        port: 2181
  zookeeper:
    znode:
      parent: /hbase

